### ISSUE TITLE
Creer un plugin en JAVA

### ISSUE THREAD

**Issue by TriXFollOoW** [TriXFollOoW/codage#1]
Main.java - CODAGE
```
package cowcube_tuto;

import java.util.logging.Logger;
import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.plugin.java.JavaPlugin;

public class Main extends JavaPlugin{
	
	public Logger log = Logger.getLogger("Minecraft");
	
	public void onEnable(){
		log.info("[CowCubeAIDE] Le plugin est en 1.0.0_BETA !");
		log.warning("[CowCubeAIDE] Attention, le plugin va s'eteindre");
		log.severe("[CowCubeAIDE] Le plugin a crash !");
	}

	public void onDisable(){
		log.info("[CowCubeAIDE] Le plugin est eteind !");
	}
	
	  public boolean onCommand(CommandSender sender, Command Cmd, String commandLabel, String[] args) {
		    if (Cmd.getName().equalsIgnoreCase("test")) {
		      sender.sendMessage(ChatColor.translateAlternateColorCodes('&', getConfig().getString("help")));
		    }
		    if (Cmd.getName().equalsIgnoreCase("aide")) {
		      sender.sendMessage("§8----------[§a§lCowCube§4§lAIDE§8]----------");
		      sender.sendMessage("§eCowCubeAIDE developped by TriX_FollOoW");
		      sender.sendMessage("§e/creatif §7| téléportation au creatif");
		      sender.sendMessage("§e/cowsky §7| téléportation au SkyBlock");
		      sender.sendMessage("§e/building §7| téléportation au Building Games");
		      sender.sendMessage("§e/pvp §7| téléportation au PvP");
		      sender.sendMessage("§e/dac §7| téléportation au Dé A Coudre");
		    }
	   
		    return true;
   }
}

```

plugin.yml - CODAGE

```
name: CowCubeTUTO
main: cowcube_tuto.Main
author: TriX_FollOoW
version: 1.0.0
website: http://trix-folloow.xyz
commands:
    test:
        description: Aide de cowcube
        permission: cowcube.help
    aide:
        description: Aide de cowcube
```

config.yml - CODAGE

`help: '§a§lFaite /aide'`
